export const drawTypeCatalog = {
  CPD: 'CPD',
  GENERAL: 'GENERAL',
};

export const resultTypeCatalog = {
  INCUMBENT: 'incumbent',
  ALTERNATE: 'alternate',
};

export const NumberOfDrawsCatalog = {
  CPD: [
    {
      group: 1,
      incumbent: 2,
      alternate: 6,
    },
    {
      group: 2,
      incumbent: 1,
      alternate: 3,
    },
    {
      group: 3,
      incumbent: 1,
      alternate: 3,
    },
    {
      group: 4,
      incumbent: 1,
      alternate: 3,
    },
  ],
  GENERAL: [
    {
      group: 1,
      incumbent: 43,
      alternate: 43,
    },
    {
      group: 2,
      incumbent: 14,
      alternate: 14,
    },
    {
      group: 3,
      incumbent: 35,
      alternate: 35,
    },
    {
      group: 4,
      incumbent: 14,
      alternate: 14,
    },
  ],
};

export const TranslateCatalog = {
  incumbent: 'titular',
  alternate: 'suplente',
};

export const groups = 3;

export const resultsTest = [
  {
    group: 1,
    drawType: 'CPD',
    resultType: 'incumbent',
    participant: 23,
    lot: 1,
  },
  {
    group: 1,
    drawType: 'CPD',
    resultType: 'incumbent',
    participant: 16,
    lot: 2,
  },
  {
    orderNumber: 1,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 4,
  },
  {
    orderNumber: 2,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 11,
  },
  {
    orderNumber: 3,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 15,
  },
  {
    orderNumber: 4,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 1,
  },
  {
    orderNumber: 5,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 12,
  },
  {
    orderNumber: 6,
    group: 1,
    drawType: 'CPD',
    resultType: 'alternate',
    participant: 17,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 683,
    lot: 3,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 87,
    lot: 4,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 37,
    lot: 5,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 153,
    lot: 6,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 83,
    lot: 7,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 576,
    lot: 8,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 374,
    lot: 9,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 28,
    lot: 10,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 416,
    lot: 11,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 234,
    lot: 12,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 255,
    lot: 13,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 121,
    lot: 14,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 482,
    lot: 15,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 359,
    lot: 16,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 97,
    lot: 17,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 566,
    lot: 18,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 665,
    lot: 19,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 232,
    lot: 20,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 462,
    lot: 21,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 32,
    lot: 22,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 110,
    lot: 23,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 617,
    lot: 24,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 532,
    lot: 25,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 631,
    lot: 26,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 358,
    lot: 27,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 708,
    lot: 28,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 19,
    lot: 29,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 261,
    lot: 30,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 320,
    lot: 31,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 544,
    lot: 32,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 61,
    lot: 33,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 690,
    lot: 34,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 437,
    lot: 35,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 649,
    lot: 36,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 554,
    lot: 37,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 296,
    lot: 38,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 48,
    lot: 39,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 643,
    lot: 40,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 176,
    lot: 41,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 235,
    lot: 42,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 506,
    lot: 43,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 548,
    lot: 44,
  },
  {
    group: 1,
    drawType: 'GENERAL',
    resultType: 'incumbent',
    participant: 530,
    lot: 45,
  },
  {
    orderNumber: 1,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 251,
  },
  {
    orderNumber: 2,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 217,
  },
  {
    orderNumber: 3,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 200,
  },
  {
    orderNumber: 4,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 519,
  },
  {
    orderNumber: 5,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 431,
  },
  {
    orderNumber: 6,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 516,
  },
  {
    orderNumber: 7,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 57,
  },
  {
    orderNumber: 8,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 188,
  },
  {
    orderNumber: 9,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 181,
  },
  {
    orderNumber: 10,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 130,
  },
  {
    orderNumber: 11,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 491,
  },
  {
    orderNumber: 12,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 574,
  },
  {
    orderNumber: 13,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 394,
  },
  {
    orderNumber: 14,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 457,
  },
  {
    orderNumber: 15,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 573,
  },
  {
    orderNumber: 16,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 715,
  },
  {
    orderNumber: 17,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 219,
  },
  {
    orderNumber: 18,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 486,
  },
  {
    orderNumber: 19,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 96,
  },
  {
    orderNumber: 20,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 616,
  },
  {
    orderNumber: 21,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 205,
  },
  {
    orderNumber: 22,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 342,
  },
  {
    orderNumber: 23,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 184,
  },
  {
    orderNumber: 24,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 684,
  },
  {
    orderNumber: 25,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 594,
  },
  {
    orderNumber: 26,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 599,
  },
  {
    orderNumber: 27,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 582,
  },
  {
    orderNumber: 28,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 237,
  },
  {
    orderNumber: 29,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 238,
  },
  {
    orderNumber: 30,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 119,
  },
  {
    orderNumber: 31,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 3,
  },
  {
    orderNumber: 32,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 391,
  },
  {
    orderNumber: 33,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 263,
  },
  {
    orderNumber: 34,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 590,
  },
  {
    orderNumber: 35,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 557,
  },
  {
    orderNumber: 36,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 514,
  },
  {
    orderNumber: 37,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 687,
  },
  {
    orderNumber: 38,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 165,
  },
  {
    orderNumber: 39,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 561,
  },
  {
    orderNumber: 40,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 44,
  },
  {
    orderNumber: 41,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 31,
  },
  {
    orderNumber: 42,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 260,
  },
  {
    orderNumber: 43,
    group: 1,
    drawType: 'GENERAL',
    resultType: 'alternate',
    participant: 108,
  },
];
