version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nuestroterreno-api-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nuestroterreno_api_db
      MYSQL_USER: joaquinvilchez
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - db
    volumes:
      - .:/nuestroterreno-api
      - /nuestroterreno-api/node_modules
    # No necesitas sobrescribir el comando aquí si ya está en Dockerfile.dev

volumes:
  db-data:

networks:
  my-network: